services:
  financer:
    build: .
    container_name: bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATA_DIR=/app/data
    volumes:
      - financer-data:/app/data
volumes:
  financer-data: